const comments = [
  "Adorable fluffball!",
  "Such a majestic feline.",
  "This cat is stealing my heart.",
  "Those eyes are mesmerizing.",
  "Pure elegance in fur form.",
  "The epitome of cuteness.",
  "Fluffy perfection!",
  "I can't handle this level of cuteness.",
  "Those whiskers are on point!",
  "The true definition of a photogenic cat.",
  "I'm in love with those tiny paws.",
  "Cuteness overload!",
  "A furry bundle of joy.",
  "Absolutely charming!",
  "That pose is everything.",
  "I want to cuddle this cat forever.",
  "The world needs more cats like this one.",
  "What a photogenic little furball!",
  "The definition of purrfection.",
  "Those ears are too cute to handle.",
  "This cat knows how to strike a pose.",
  "A cat this cute should be illegal!",
  "I'm convinced cats are magical creatures.",
  "I would give anything for a boop of that nose.",
  "The cuteness factor is off the charts!",
];

export default { comments };
